"""The Python half of the p95 cross-check.

tests/tolerances/qwen3-tts.json states the hole this closes in its own words:
the end-to-end test "transcribes the p95 statistic from the validator by hand
(numpy-linear percentile of the per-frame L2 relative to the oracle frame's own
norm), and the two implementations have NO registered cross-check -- they were
compared once, manually, on the same buffers, agreeing to every printed digit,
and could drift apart silently afterwards."

The two implementations are scripts/validate-qwen3-tts-codec_encoder.py (numpy)
and tests/qwen3_tts_percentile.h (a deliberate reimplementation of numpy's
"linear" interpolation in C++). tests/qwen3_tts_percentile_test.cpp is the other
half of this pair, and both read
tests/fixtures/qwen3-tts/percentile-cross-check.json.

WHAT EACH HALF ACTUALLY PROVES, stated rather than blurred, because the two are
not symmetric:

  * The C++ half proves the C++ matches numpy. numpy is a third party to it,
    so that is a real comparison.
  * This half CANNOT prove numpy matches numpy. The fixture's expected values
    were generated by numpy, so recomputing them with numpy is circular in the
    obvious way -- and it is kept anyway for the one thing it does catch: a
    numpy VERSION change. The fixture was generated under numpy 1.26.4 and both
    locked environments pin that; if a future bump changes `np.percentile`'s
    default interpolation, or its behaviour at n = 1 or on ties, this fails and
    the C++ side's target is known to have moved.
  * The part of this file that is not circular is
    `test_the_validator_still_computes_this_statistic`, which reads the
    validator's source and pins the three expressions the fixture describes. A
    redesign that changes the statistic in the validator without touching this
    test fails there -- which is the coupling Plan 4 Task 3 needs, since it is
    about to change the statistic in both places at once.
"""

from __future__ import annotations

import json
from pathlib import Path
import unittest

import numpy as np


REPO_ROOT = Path(__file__).resolve().parents[2]
FIXTURE = REPO_ROOT / "tests" / "fixtures" / "qwen3-tts" / "percentile-cross-check.json"
VALIDATOR = REPO_ROOT / "scripts" / "validate-qwen3-tts-codec_encoder.py"

# Tight enough that an interpolation change cannot hide -- nearest-rank moves
# the `n2` entry from 2.9 to 3.0 -- and loose enough not to pin the last bit of
# a decimal transcription.
TOLERANCE = 1e-12


def load_fixture() -> dict:
    return json.loads(FIXTURE.read_text(encoding="utf-8"))


class PercentileAgreement(unittest.TestCase):
    def setUp(self) -> None:
        self.fixture = load_fixture()

    def test_fixture_is_committed(self) -> None:
        self.assertTrue(FIXTURE.is_file(), f"missing {FIXTURE}")
        self.assertEqual(
            self.fixture["schema"],
            "synthesize-qwen3-tts-percentile-cross-check-v1",
        )

    def test_percentile_entries_agree(self) -> None:
        """Every committed percentile value, recomputed with numpy."""
        block = self.fixture["percentile"]
        percent = block["percent"]
        self.assertEqual(percent, 95.0)
        self.assertEqual(block["interpolation"], "linear")

        consumed = 0
        for entry in block["entries"]:
            with self.subTest(entry=entry["id"]):
                values = np.asarray(entry["values"], dtype=np.float64)
                self.assertEqual(
                    values.size,
                    entry["n"],
                    f"{entry['id']}: declares n = {entry['n']} and carries {values.size} values",
                )
                measured = float(np.percentile(values, percent))
                self.assertAlmostEqual(
                    measured,
                    entry["expected"],
                    delta=TOLERANCE * max(1.0, abs(entry["expected"])),
                    msg=f"{entry['id']}: numpy now returns {measured!r}, the fixture "
                    f"committed {entry['expected']!r}",
                )
            consumed += 1

        # Against the DECLARED count, not against len(entries) it just iterated:
        # a test that iterates a JSON array and asserts nothing about its length
        # passes trivially when the array shrinks.
        self.assertEqual(
            consumed,
            block["entry_count"],
            "consumed a different number of entries than the fixture declares",
        )

    def test_the_rank_positions_span_both_branches(self) -> None:
        """The fixture must exercise interpolation, not only the easy case.

        The 95th percentile's rank is 0.95 * (n - 1). When that is an integer
        the answer is a sample and a nearest-rank implementation agrees; only
        the fractional positions separate the two definitions. A fixture of
        integer positions would pass under an implementation this pair exists
        to reject.
        """
        entries = self.fixture["percentile"]["entries"]
        fractional = [e for e in entries if abs(e["rank_position"] % 1.0) > 1e-12]
        integral = [e for e in entries if abs(e["rank_position"] % 1.0) <= 1e-12]
        self.assertGreaterEqual(len(fractional), 4, "too few interpolating entries")
        self.assertGreaterEqual(len(integral), 1, "no entry lands on a sample")

    def test_reconstruction_operand_order(self) -> None:
        """The denominator is the RIGHT operand's norm, and swapping is visible.

        This is the half a fixture of pre-computed percentile inputs cannot
        reach: `reconstruction_p95_relative` is not just a percentile, it
        divides each frame's L2 deviation by the ORACLE frame's own norm. The
        expression below is the validator's, at
        scripts/validate-qwen3-tts-codec_encoder.py:251-255, where `norms` is
        taken over `b`.
        """
        block = self.fixture["reconstruction"]
        consumed = 0
        for entry in block["entries"]:
            with self.subTest(entry=entry["id"]):
                frames = entry["frames"]
                projected = entry["projected"]
                port = np.asarray(entry["port"], dtype=np.float64).reshape(frames, projected)
                oracle = np.asarray(entry["oracle"], dtype=np.float64).reshape(frames, projected)

                def p95_relative(a: np.ndarray, b: np.ndarray) -> float:
                    per_frame = np.linalg.norm(a - b, axis=-1)
                    norms = np.linalg.norm(b, axis=-1)
                    relative = per_frame / norms
                    return float(np.percentile(relative, 95))

                forward = p95_relative(port, oracle)
                swapped = p95_relative(oracle, port)

                self.assertAlmostEqual(
                    forward,
                    entry["expected_p95_relative"],
                    delta=TOLERANCE * max(1.0, abs(entry["expected_p95_relative"])),
                )
                self.assertAlmostEqual(
                    swapped,
                    entry["expected_p95_relative_operands_swapped"],
                    delta=TOLERANCE * max(1.0, abs(entry["expected_p95_relative_operands_swapped"])),
                )
                # The two must be far apart, or the order inversion in the C++
                # test would be an assertion that cannot fail.
                self.assertGreater(
                    abs(forward - swapped),
                    1e-3 * max(abs(forward), abs(swapped)),
                    "the operand-order inversion is not detectable on this pair",
                )
            consumed += 1
        self.assertEqual(consumed, block["entry_count"])

    def test_masked_entries_agree(self) -> None:
        """The masked statistic, over the reconstruction block's own pair.

        Plan 4 Task 3 made this the gated quantity and it reached no `unit`
        target until the mask block existed: `reconstruction_p95_relative_masked`
        was called only from tests/qwen3_tts_icl_real.cpp, which is
        integration-tier. A null expectation is a REFUSAL rather than a zero --
        the C++ half returns NaN, which compares false against every bound.
        """
        block = self.fixture["mask"]
        base = self.fixture["reconstruction"]["entries"][0]
        frames = block["frames"]
        projected = block["projected"]
        self.assertEqual(frames, base["frames"])
        self.assertEqual(projected, base["projected"])
        port = np.asarray(base["port"], dtype=np.float64).reshape(frames, projected)
        oracle = np.asarray(base["oracle"], dtype=np.float64).reshape(frames, projected)

        def p95_masked(keep: list[int]) -> float | None:
            selected = np.asarray(keep, dtype=bool)
            if not selected.any():
                return None
            a = port[selected]
            b = oracle[selected]
            per_frame = np.linalg.norm(a - b, axis=-1)
            norms = np.linalg.norm(b, axis=-1)
            return float(np.percentile(per_frame / norms, 95))

        consumed = 0
        refusals = 0
        for entry in block["entries"]:
            with self.subTest(entry=entry["id"]):
                keep = entry["keep"]
                self.assertEqual(len(keep), frames)
                measured = p95_masked(keep)
                expected = entry["expected_p95_relative_masked"]
                if expected is None:
                    self.assertEqual(sum(keep), 0, "a null expectation must mean an empty mask")
                    self.assertIsNone(measured)
                    refusals += 1
                else:
                    self.assertGreater(sum(keep), 0)
                    self.assertIsNotNone(measured)
                    self.assertAlmostEqual(
                        measured, expected, delta=TOLERANCE * max(1.0, abs(expected))
                    )
                    if all(keep):
                        # An all-ones mask is the unmasked statistic, and the
                        # fixture records that value in the other block.
                        self.assertAlmostEqual(
                            measured,
                            base["expected_p95_relative"],
                            delta=TOLERANCE * max(1.0, abs(measured)),
                        )
            consumed += 1
        self.assertEqual(consumed, block["entry_count"])
        self.assertGreaterEqual(refusals, 1, "the fixture carries no empty-mask case")

    def test_codebook_masks_agree(self) -> None:
        """Which COLUMNS each branch reads, which is the whole of this mask.

        Column 0 is semantic; 1..groups-1 are acoustic. The fixture places the
        faults so each branch keeps a frame the other drops, so a mask that
        ignored the branch flag matches neither.
        """
        block = self.fixture["codebook"]
        frames = block["frames"]
        groups = block["groups"]
        upstream = np.asarray(block["upstream"], dtype=np.int32).reshape(frames, groups)
        oracle = np.asarray(block["oracle"], dtype=np.int32).reshape(frames, groups)

        def keep_mask(semantic: bool) -> list[int]:
            if semantic:
                differ = upstream[:, 0] != oracle[:, 0]
            else:
                differ = (upstream[:, 1:] != oracle[:, 1:]).any(axis=1)
            return [0 if flipped else 1 for flipped in differ]

        by_branch: dict[bool, list[int]] = {}
        consumed = 0
        for entry in block["entries"]:
            with self.subTest(entry=entry["id"]):
                measured = keep_mask(entry["semantic"])
                self.assertEqual(measured, entry["expected_keep"])
                by_branch[bool(entry["semantic"])] = measured
            consumed += 1
        self.assertEqual(consumed, block["entry_count"])

        self.assertEqual(set(by_branch), {True, False}, "both branches must be present")
        semantic, acoustic = by_branch[True], by_branch[False]
        self.assertTrue(
            any(s and not a for s, a in zip(semantic, acoustic)),
            "no frame is kept by the semantic branch alone",
        )
        self.assertTrue(
            any(a and not s for s, a in zip(semantic, acoustic)),
            "no frame is kept by the acoustic branch alone",
        )

    def test_the_validator_still_computes_this_statistic(self) -> None:
        """The non-circular half: pin the validator's own expressions.

        This is what makes the fixture describe the SHIPPED statistic rather
        than one this test invented. Plan 4 Task 3 is about to redesign the
        statistic; when it does, these strings stop matching and this test
        fails, which is the intended signal to extend the fixture in the same
        change rather than to let the two implementations part company.
        """
        source = VALIDATOR.read_text(encoding="utf-8")
        for expression in (
            "per_frame = np.linalg.norm(a - b, axis=-1)",
            "norms = np.linalg.norm(b, axis=-1)",
            "relative = per_frame / norms",
            "np.percentile(relative, 95)",
            # And the mask, which is what Plan 4 Task 3 made the gated quantity.
            # Column 0 is the semantic branch, 1.. the acoustic one; a redesign
            # that moved that split without touching the fixture fails here.
            "differ[:, 0] if branch == 0 else differ[:, 1:].any(axis=1)",
        ):
            self.assertIn(
                expression,
                source,
                f"{VALIDATOR.name} no longer contains {expression!r}. If the statistic was "
                "redesigned, extend tests/fixtures/qwen3-tts/percentile-cross-check.json and "
                "both halves of this cross-check in the same change.",
            )


if __name__ == "__main__":
    unittest.main()
