#!/usr/bin/env python3
"""Generate src/unicode-ranges.h from the running Python's Unicode tables.

The Qwen byte-pair pre-tokenizer splits on `\\p{L}`, `\\p{N}` and `\\s`, which no
C++ standard library exposes. Classifying by hand would be wrong at the edges --
and the edges are exactly where a text-to-speech input lands, since a wrong split
produces different tokens and therefore different, still-plausible speech.

The tables are emitted as sorted, merged code point ranges and searched by
bisection. Regenerate with:

    uv run --project scripts/envs/vits --locked python scripts/generate-unicode-ranges.py
"""

from __future__ import annotations

import sys
import unicodedata
from pathlib import Path

MAX_CODEPOINT = 0x110000


def ranges(predicate) -> list[tuple[int, int]]:
    out: list[tuple[int, int]] = []
    start: int | None = None
    for codepoint in range(MAX_CODEPOINT):
        if predicate(codepoint):
            if start is None:
                start = codepoint
        elif start is not None:
            out.append((start, codepoint - 1))
            start = None
    if start is not None:
        out.append((start, MAX_CODEPOINT - 1))
    return out


def emit(handle, name: str, values: list[tuple[int, int]], comment: str) -> None:
    handle.write(f"// {comment}\n")
    handle.write(f"inline constexpr CodepointRange {name}[] = {{\n")
    for index in range(0, len(values), 4):
        row = ", ".join(f"{{ 0x{low:X}, 0x{high:X} }}" for low, high in values[index : index + 4])
        handle.write(f"    {row},\n")
    handle.write("};\n\n")


def main() -> int:
    letters = ranges(lambda cp: unicodedata.category(chr(cp)).startswith("L"))
    numbers = ranges(lambda cp: unicodedata.category(chr(cp)).startswith("N"))
    spaces = ranges(lambda cp: chr(cp).isspace())

    target = Path(__file__).resolve().parent.parent / "src" / "unicode-ranges.h"
    with target.open("w", encoding="utf-8") as handle:
        handle.write("// Generated by scripts/generate-unicode-ranges.py. Do not edit.\n")
        handle.write(f"//\n// Unicode {unicodedata.unidata_version} letter, number and whitespace\n")
        handle.write("// ranges, for the byte-pair pre-tokenizer's character classes.\n\n")
        handle.write("#pragma once\n\n#include <cstdint>\n\nnamespace synth {\n\n")
        handle.write("struct CodepointRange {\n    uint32_t low;\n    uint32_t high;\n};\n\n")
        emit(handle, "kUnicodeLetterRanges", letters, f"General category L*: {len(letters)} ranges.")
        emit(handle, "kUnicodeNumberRanges", numbers, f"General category N*: {len(numbers)} ranges.")
        emit(handle, "kUnicodeWhitespaceRanges", spaces,
             f"What Python's str.isspace reports, which is what the reference splits on: "
             f"{len(spaces)} ranges.")
        handle.write("}  // namespace synth\n")
    print(f"wrote {target} ({len(letters)} letter, {len(numbers)} number, {len(spaces)} space ranges)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
